# Generated by pip2nix 0.7.0.dev1
# Adjust to your needs, e.g. to provide C libraries.

{ pkgs, basePythonPackages }:

self: super: {

  # Avoid infinite recursion due to setuptools
  inherit (basePythonPackages)
    setuptools;
}
