name: Build Nix macOS env

on:
  pull_request:
    paths:
    - '**'
    - '!**.md'
  push:
    paths:
    - '**'
    - '!**.md'
  schedule:
    - cron: '0 0 * * 0' # Every Sunday at midnight UTC

jobs:

  build-macos-env:
    name: Build/cache macOS Nix env
    runs-on: macos-latest
    env:
      NIX_PATH: darwin-config=/Users/runner/.config/nixpkgs/darwin/ci.nix:nixpkgs=/Users/runner/.nix-defexpr/channels/nixpkgs:/Users/runner/.nix-defexpr/channels

    steps:

    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Symlink Nix directories
      run: |
        ln -s ${{ github.workspace }} ~/.config/nixpkgs
        ln -s ${{ github.workspace }}/nix/nix-defexpr ~/.nix-defexpr

    - name: Install Nix
      uses: cachix/install-nix-action@v12
      with:
        extra_nix_config: |
          substituters = https://cache.nixos.org/ https://hydra.iohk.io
          trusted-public-keys = cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY= hydra.iohk.io:f/Ea+s+dFdN+3Y/G+FDgSq+a5NEWhJGzdjvKNGv0/EQ=

    - name: Setup Cachix
      uses: cachix/cachix-action@v8
      with:
        name: malo
        extraPullNames: iohk
        signingKey: ${{ secrets.CACHIX_SIGNING_KEY }}

    - name: If scheduled, update sources
      if: ${{ github.event_name == 'schedule' && success() }}
      run: |
        nix-shell -p niv --run "niv update"

    - name: Build and switch to nix-darwin env
      run: |
        # Create /run directory
        echo -e "run\tprivate/var/run" | sudo tee -a /etc/synthetic.conf >/dev/null
        /System/Library/Filesystems/apfs.fs/Contents/Resources/apfs.util -B 2>/dev/null || true
        # Prevent conflict between Cachix installed by workflow and the one installed in the config
        nix-env --set-flag priority 1 cachix
        # Update brew (required for programs.brew-bundle module)
        brew update
        # Build and switch to nix-darwin env
        $(nix-build '<darwin>' -A system --no-out-link)/sw/bin/darwin-rebuild switch

    - name: If scheduled, push commit with updated sources
      if: ${{ github.event_name == 'schedule' && success() }}
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com
        git aa
        git cm "Update sources"
        git push
