name: Build Nix envs

on:
  pull_request:
    paths:
    - '**'
    - '!**.md'
  push:
    paths:
    - '**'
    - '!**.md'
  schedule:
    - cron: '0 0 * * 0' # Every Sunday at midnight UTC

jobs:

  build-macos-env:
    name: Build/cache macOS Nix env
    runs-on: macos-latest

    steps:

    - name: Checkout repository
      uses: actions/checkout@v2
      with:
          # Nix Flakes doesn't work on shallow clones
          fetch-depth: 0
    - uses: cachix/install-nix-action@v12
      with:
        install_url: https://github.com/numtide/nix-flakes-installer/releases/download/nix-2.4pre20201221_9fab14a/install
        extra_nix_config: |
          experimental-features = nix-command flakes

    - name: Setup Cachix
      uses: cachix/cachix-action@v8
      with:
        name: malo
        signingKey: ${{ secrets.CACHIX_SIGNING_KEY }}

    - name: If scheduled, update sources
      if: ${{ github.event_name == 'schedule' && success() }}
      run: |
        nix flake update

    - name: Build and switch to nix-darwin env
      run: |
        # Create /run directory
        echo -e "run\tprivate/var/run" | sudo tee -a /etc/synthetic.conf >/dev/null
        /System/Library/Filesystems/apfs.fs/Contents/Resources/apfs.util -B 2>/dev/null || true
        # Build and switch to bootstrap config
        nix build .#darwinConfigurations.bootstrap.system
        ./result/sw/bin/darwin-rebuild switch --flake .#bootstrap
        # Build and switch to full config
        /run/current-system/sw/bin/fish -c 'darwin-rebuild switch --flake .#githubCI'

    - name: If scheduled, push commit with updated sources
      if: ${{ github.event_name == 'schedule' && success() }}
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com
        git aa
        git cm "Update sources"
        git push

  build-linux-env:
    name: Build/cache Linux Nix env
    runs-on: ubuntu-latest

    steps:

    - name: Checkout repository
      uses: actions/checkout@v2
      with:
          # Nix Flakes doesn't work on shallow clones
          fetch-depth: 0
    - uses: cachix/install-nix-action@v12
      with:
        install_url: https://github.com/numtide/nix-flakes-installer/releases/download/nix-2.4pre20201221_9fab14a/install
        extra_nix_config: |
          experimental-features = nix-command flakes
          substituters = https://cache.nixos.org/ https://hydra.iohk.io
          trusted-public-keys = cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY= hydra.iohk.io:f/Ea+s+dFdN+3Y/G+FDgSq+a5NEWhJGzdjvKNGv0/EQ=

    - name: Setup Cachix
      uses: cachix/cachix-action@v8
      with:
        name: malo
        extraPullNames: iohk
        signingKey: ${{ secrets.CACHIX_SIGNING_KEY }}

    - name: Build and switch to home-manager env
      run: |
        # Prevent conflict between Cachix installed by workflow and the one installed in the config
        nix-env --set-flag priority 1 cachix
        # Build and switch to home-manager env
        nix build .#vm; ./result/activate
